// <auto-generated />
using System;
using Hemsida_ASP.NET.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hemsida_ASP.NET.Migrations.Data
{
    [DbContext(typeof(DataContext))]
    [Migration("20230528095917_Added seeding for products")]
    partial class Addedseedingforproducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hemsida_ASP.NET.Models.Entities.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Hemsida_ASP.NET.Models.Entities.ContactMessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Hemsida_ASP.NET.Models.Entities.ProductEntity", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ArticleId = "A12395B",
                            Description = "These running shoes are designed for optimal performance and comfort. With a lightweight and breathable mesh upper, these shoes provide excellent ventilation during intense runs. The cushioned midsole offers responsive and energy-returning support, reducing fatigue and enhancing your stride.",
                            Ingress = "Fabric shoes perfect for jogging and walking",
                            Price = 250.00m,
                            ProductImage = "Image1.jpg",
                            ProductName = "Running Shoes",
                            VendorName = "Adidas"
                        },
                        new
                        {
                            ArticleId = "C167452B",
                            Description = "This woolen winter hat is the perfect accessory to keep you cozy and stylish during cold weather. Made from high-quality, soft wool, this hat offers excellent insulation and warmth. Its thick and plush construction provides superior protection against chilly winds and frosty temperatures. The hat features a snug fit and a foldable cuff, allowing you to adjust the coverage according to your preference.",
                            Ingress = "75% Pure Wool Hat for winter weather",
                            Price = 125.00m,
                            ProductImage = "Image2.jpg",
                            ProductName = "Wool Hat",
                            VendorName = "Ellos"
                        },
                        new
                        {
                            ArticleId = "F129753R",
                            Description = "The 'SilkGlow' silken scarf is a luxurious accessory that adds elegance and sophistication to any outfit. Made from premium-quality silk, this scarf offers a smooth and soft touch against the skin. Its lightweight and flowing fabric drapes beautifully, creating a graceful and graceful look. The 'SilkGlow' scarf features a vibrant and lustrous sheen that catches the light, adding a touch of glamour to your ensemble.",
                            Ingress = "Silken scarf for summer evenings",
                            Price = 300.00m,
                            ProductImage = "Image3.jpg",
                            ProductName = "Silk Scarf",
                            VendorName = "Zara"
                        });
                });

            modelBuilder.Entity("Hemsida_ASP.NET.Models.Entities.ProductTagEntity", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");

                    b.HasData(
                        new
                        {
                            ArticleId = "A12395B",
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = "A12395B",
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = "C167452B",
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = "C167452B",
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = "F129753R",
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = "F129753R",
                            TagId = 2
                        });
                });

            modelBuilder.Entity("Hemsida_ASP.NET.Models.Entities.TagEntity", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            TagName = "New"
                        },
                        new
                        {
                            TagId = 2,
                            TagName = "Popular"
                        },
                        new
                        {
                            TagId = 3,
                            TagName = "Featured"
                        });
                });

            modelBuilder.Entity("Hemsida_ASP.NET.Models.Entities.ContactMessageEntity", b =>
                {
                    b.HasOne("Hemsida_ASP.NET.Models.Entities.ContactEntity", "Contact")
                        .WithMany("Messages")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Hemsida_ASP.NET.Models.Entities.ProductTagEntity", b =>
                {
                    b.HasOne("Hemsida_ASP.NET.Models.Entities.ProductEntity", "Product")
                        .WithMany("Tags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hemsida_ASP.NET.Models.Entities.TagEntity", "Tag")
                        .WithMany("Products")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hemsida_ASP.NET.Models.Entities.ContactEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Hemsida_ASP.NET.Models.Entities.ProductEntity", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Hemsida_ASP.NET.Models.Entities.TagEntity", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
